### ISSUE TITLE
合成物品数量强制改变

### ISSUE THREAD

**Issue by ainlzj** [12345-mcpython/stackone#18]
物品合成本该木头合成4个木板，但模组会强制让你合成变成一个木板，
并且如有其他模组会导致有些模组需要一定数量的所需物品会导致无法做到下一步

**Comment by 12345-mcpython** [comment]
1.0.1版本已经移除这个特性

**Comment by 12345-mcpython** [comment]
说实话如果真的需要按shift可以跳过限制，直接取出4个木板

**Comment by ainlzj** [comment]
> 说实话如果真的需要按转变可以跳过限制,直接取出4个木板

      物品栏是不能堆叠，但你也不能把合成栏也弄弄掉呀，某些模组木头是分解出这么多方块，为何不直接把木头分解数量设置成一块？你的模组核心思想是物品栏的物品禁止堆叠？还是要把MC所有物品gui禁止堆叠？1.0.0取出来禁止堆叠那不就算失效了？shift下来为什么不是分解后占4个格子呢？

比如说我的整合包吧，我的整合包是那种偏真实硬核的那种整合，界面上的所有HUD统统弄消失，温度饥饿口渴什么的都弄消失，一切全靠听。我又弄了个锁物品栏的格子的模组，锁剩九个格子，但这9个格子我觉得还是有不够恶心，直到看到你这个模组，我觉得恶心又可以再进一步，但是本模组也有局限性吧，对于合成表分解数量的确是有点问题，某些模组界面需要放置这么多的所需物品但是就是放不了然后就GG了，那有没有想过对于其他模组界面通过一个一个点击堆成X64呢?
